name: PR
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  dependencies:
    uses: ./.github/workflows/shared-changesets-dependencies.yml
    secrets:
      githubToken: ${{ secrets.PINAX_BOT_GITHUB_TOKEN }}
      gpg_private_key: ${{ secrets.PINAX_BOT_PGP_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.PINAX_BOT_PGP_PASSPHRASE }}

