# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      installDependencies:
        type: boolean
        default: false
      preCommit:
        type: string
        required: false
      packageManager:
        type: string
        required: false
        default: yarn
      packageManagerVersion:
        type: string
        description: Package manager version
        required: false
        default: ''
      nodeVersion:
        required: false
        type: string
        default: '20'
      gitUserEmail:
        required: false
        type: string
        default: ''
      gitUserName:
        required: false
        type: string
        default: ''
    secrets:
      githubToken:
        required: true
      PINAX_BOT_PGP_PRIVATE_KEY:
        required: true
      PINAX_BOT_PGP_PASSPHRASE:
        required: true

jobs:
  changeset:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.githubToken }}

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PINAX_BOT_PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.PINAX_BOT_PGP_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create/Update Changesets
        uses: pinax-network/changesets-dependencies-action@v1.3.0
        with:
          preCommit: ${{ inputs.preCommit }}
          gitUserEmail: ${{ inputs.gitUserEmail }}
          gitUserName: ${{ inputs.gitUserName }}
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
